### ISSUE TITLE
Improve automated dev tests

### ISSUE THREAD

**Issue by abcorrea** [abcorrea/powerlifted#12]
We would like to improve the tests in `dev/`. Right now, the tests do not work after the integration with different exit codes. Ideally, we would like to add the following:

- The tests check the plan length found and check it with the expected known value
- The tests check if the plan found is valid using VAL
- The tests print time and memory usages so we can compare performance quickly between commits
- The tests have an easier interface than the current one

We probably also want to split into different tests (i.e., check translator, search, and all planner components).

**Comment by gfrances** [comment]
For the Python translator tests I'd definitely go with pytest. For C++ test I would also consider some testing framework, but if you have already something that works there, let's go with that!

**Comment by abcorrea** [comment]
For C++ I only know unit testing tools (like Google testing), but the tests we are running now are basically just checking output and plans and verifying if they make sense. Do you think this is fine enough for this issue or should we extend it?

**Comment by gfrances** [comment]
no, that sounds great :-)
