### ISSUE TITLE
Planner fails with `terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at`

### ISSUE THREAD

**Issue by peperunas** [abcorrea/powerlifted#47]
Hello!

I am new to the planning domain and have been directed to lifted planners as an alternative to grounded planners.

I am trying to solve a task - that I am sure has a solution - with the lifted planner, as other grounded planners are unable to ground the task without immense amount of RAM (250+ GB were not enough). The only solution I found to get a solution was to decrease the number of objects and predicates of my task: doing this would undermine the core of the project I am working on and it is not a viable solution.

When trying to solve the task with the default options, I get the following error:

```
Parsing...
Parsing: [0.020s CPU, 0.023s wall-clock]
Processing task micronix-problem-root
Normalizing task... [0.000s CPU, 0.002s wall-clock]
Compiling types into unary predicates... [0.000s CPU, 0.003s wall-clock]
Checking static predicates... [0.000s CPU, 0.000s wall-clock]
Initial state size: 1933
WARNING: file output.lifted already exists, it will be overwritten
Total translation time: 0.090s
Executing "/home/giulio/dev/harden/powerlifted/builds/debug/search/search -f output.lifted -s alt-bfws1 -e ff -g yannakakis -r sparse --seed 1 --plan-file plan"
Initializing planner
Reading task description file.
micronix micronix-problem-root
Total number of types: 13
Total number of predicates: 45
Total number of objects: 526
Total number of atoms in the initial state: 4628
Total number of fluent atoms in the goal state: 1
Total number of action schemas: 44
IMPORTANT: Assuming that negative effects are always listed first. (This is guaranteed by the default translator.)
Creating search factory for method alt-bfws1...
Using Dual-Queue BFWS
Creating heuristic factory...
Iteration removed 162 equivalent rules.
Iteration removed 0 equivalent rules.
Total number of static atoms in the EDB: 2695
Total number of rules: 151
Creating successor generator factory...
Starting AlternatedBFWS
Iteration removed 162 equivalent rules.
Iteration removed 0 equivalent rules.
Total number of static atoms in the EDB: 2695
Total number of rules: 151
Initial h-add value of the task: 2147483647
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Iteration finished correctly.
```

I also tried every other `-e` and `-s` flags to no avail. Additionally, I also tried to use the `Minecraft-Saar` fork but I found no differences. 

I would share the problem file and domain privately, if possible. Please let me know what I can do to troubleshoot the issue.

Thank you very much!

**Comment by abcorrea** [comment]
Hi Giulio,

Could you send me the instances privately? (if you need my email: augusto.blaascorrea@unibas.ch)

I'm afraid that this is related to the fragment of PDDL you're using, as Powerlifted supports a very limited portion of PDDL featured (basically STRIPS). Even if that's the case, there are a few things we could try off-the-shelf, and having the instances probably would make the process quicker. 

Also: are you using the master branch or are you using the IPC submission? From the log it seems to me that you're running a portfolio, so I believe it is the IPC one? 

Cheers 
Augusto

**Comment by abcorrea** [comment]
This issue was solved via email.
