### ISSUE TITLE
gitignore file deletes plan_manager files

### ISSUE THREAD

**Issue by DillonZChen** [abcorrea/powerlifted#55]
Line 10 of the .gitignore matches the `plan_manager.h` and `plan_manager.cc` files in the source directory which caused some weird problems for me when installing powerlifted for other projects. 

An easy fix to this unwanted side effect would just be to remove this line.

**Comment by abcorrea** [comment]
Commit  [9c93ad3](https://github.com/abcorrea/powerlifted/commit/9c93ad30572f725eee9e8dc3d50f6ab3441f9596) solves the issue.
